name:                ex01-parsing-practice
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/k-bx/ex01-parsing-practice#readme
license:             BSD3
author:              Kostiantyn Rybnikov
maintainer:          k-bx@k-bx.com
copyright:           Kostiantyn Rybnikov
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - parsers
  - trifecta

executables:
  ex01-parsing-practice:
    source-dirs:      src
    main:             Main.hs
